---
x-airflow-common:
  &airflow-common
  # In order to add custom dependencies or upgrade provider distributions you can use your extended image.
  # Comment the image line, place your Dockerfile in the directory where you placed the docker-compose.yaml
  # and uncomment the "build" line below, Then run `docker-compose build` to build the images.
  build: .
  # image: gitlab-registry.ifremer.fr/dev-ops/isival/airflow-plateforme:3.0.6
  # In order to force override variables from official Airflow compose.yml we need to override these here
  # for any other variables, you just need to add it to airflow_override_config in vars.yml.
  environment:
    &airflow-common-env
    AIRFLOW__CORE__LOAD_EXAMPLES: false
  volumes:
    - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
    - ${AIRFLOW_PROJ_DIR:-.}/config:/opt/airflow/config
    - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
    - ${AIRFLOW_PROJ_DIR:-.}/data:/opt/airflow/data
  user: "${AIRFLOW_UID:-50000}:0"
  env_file: ".env"
  depends_on:
    &airflow-common-depends-on
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy

services:
  airflow-apiserver:
    <<: [ *airflow-common ]
  airflow-scheduler:
    <<: [ *airflow-common ]
  airflow-dag-processor:
    <<: [ *airflow-common ]
  airflow-worker:
    <<: [ *airflow-common ]
  airflow-triggerer:
    <<: [ *airflow-common ]
